# Generated by Django 6.0.5 on 2026-06-30 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='grupos_participante', to=settings.AUTH_USER_MODEL),
        ),
    ]
