# Generated by Django 6.0.5 on 2026-07-20 01:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_group_participantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El monto debe ser mayor que cero.')])),
                ('fecha_gasto', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='expenses.group')),
                ('pagado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_pagados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(related_name='gastos_compartidos', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_gasto', '-fecha_registro'],
            },
        ),
    ]
