# Generated by Django 6.0.5 on 2026-07-20 03:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisiones', to='expenses.expense')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisiones_gastos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['participante__username'],
                'constraints': [models.UniqueConstraint(fields=('gasto', 'participante'), name='division_unica_por_gasto_participante')],
            },
        ),
    ]
