# Generated by Django 6.0.5 on 2026-07-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
