# Generated by Django 6.0.5 on 2026-07-25 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_group_fecha_fin_group_fecha_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='expenses.group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias_grupos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_ingreso', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('grupo', 'usuario'), name='membresia_activa_unica_por_grupo_usuario'), models.CheckConstraint(condition=models.Q(models.Q(('activo', True), ('fecha_salida__isnull', True)), models.Q(('activo', False), ('fecha_salida__isnull', False)), _connector='OR'), name='membresia_estado_fecha_salida_consistentes')],
            },
        ),
    ]
