# Generated by Django 6.0.5 on 2026-07-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_migrar_participantes_a_membresias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='pagado_por',
        ),
    ]
