# Generated by Django 6.0.5 on 2026-07-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_remove_expense_pagado_por'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='pago_pagador_receptor_diferentes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receptor',
        ),
    ]
