# Generated by Django 6.0.5 on 2026-07-26 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_remove_payment_pago_pagador_receptor_diferentes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('enlace', models.CharField(blank=True, default='', max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
                'indexes': [models.Index(fields=['usuario', 'leida', '-fecha_creacion'], name='notif_usuario_estado_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('fecha_lectura__isnull', True), ('leida', False)), models.Q(('fecha_lectura__isnull', False), ('leida', True)), _connector='OR'), name='notificacion_lectura_fecha_consistente')],
            },
        ),
    ]
