# Generated by Django 6.0.5 on 2026-07-26 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nombre', models.CharField(max_length=100)),
                ('usuario_username', models.CharField(max_length=150)),
                ('tipo_accion', models.CharField(choices=[('actividad_creada', 'Actividad creada'), ('actividad_actualizada', 'Actividad actualizada'), ('participante_ingreso', 'Participante agregado'), ('participante_retiro', 'Participante retirado'), ('participante_reingreso', 'Participante reingresado'), ('gasto_creado', 'Gasto creado'), ('gasto_actualizado', 'Gasto actualizado'), ('gasto_eliminado', 'Gasto eliminado'), ('pago_creado', 'Pago creado')], max_length=40)),
                ('descripcion', models.TextField()),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='expenses.group')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_evento', '-id'],
                'indexes': [models.Index(fields=['grupo', '-fecha_evento'], name='hist_grupo_fecha_idx'), models.Index(fields=['grupo', 'tipo_accion', '-fecha_evento'], name='hist_grupo_tipo_idx')],
            },
        ),
    ]
