# Generated by Django 6.0.5 on 2026-07-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_activityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fecha_cierre_automatico',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='tipo_accion',
            field=models.CharField(choices=[('actividad_creada', 'Actividad creada'), ('actividad_actualizada', 'Actividad actualizada'), ('actividad_cerrada_automaticamente', 'Actividad cerrada automáticamente'), ('participante_ingreso', 'Participante agregado'), ('participante_retiro', 'Participante retirado'), ('participante_reingreso', 'Participante reingresado'), ('gasto_creado', 'Gasto creado'), ('gasto_actualizado', 'Gasto actualizado'), ('gasto_eliminado', 'Gasto eliminado'), ('pago_creado', 'Pago creado')], max_length=40),
        ),
    ]
