# Generated by Django 6.0.5 on 2026-07-26 19:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_group_fecha_cierre_automatico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fecha_generacion_saldos',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ClosingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nombre', models.CharField(max_length=100)),
                ('participante_username', models.CharField(max_length=150)),
                ('cuota_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('saldado', 'Saldado')], max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_cierre', to='expenses.group')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_cierre_actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['participante_username', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nombre', models.CharField(max_length=100)),
                ('participante_username', models.CharField(max_length=150)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_generadas', to='expenses.group')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas_actividades', to=settings.AUTH_USER_MODEL)),
                ('saldo_cierre', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deuda', to='expenses.closingbalance')),
            ],
            options={
                'ordering': ['-fecha_generacion', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='closingbalance',
            index=models.Index(fields=['grupo', 'estado'], name='saldo_grupo_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='closingbalance',
            index=models.Index(fields=['participante', 'estado'], name='saldo_usuario_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='closingbalance',
            constraint=models.UniqueConstraint(fields=('grupo', 'participante'), name='saldo_cierre_unico_por_grupo_participante'),
        ),
        migrations.AddConstraint(
            model_name='closingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('cuota_total__gte', Decimal('0.00'))), name='saldo_cierre_cuota_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='closingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('total_pagado__gte', Decimal('0.00'))), name='saldo_cierre_pago_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='closingbalance',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_pendiente__gte', Decimal('0.00'))), name='saldo_cierre_pendiente_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['participante', 'estado', '-fecha_generacion'], name='deuda_usuario_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['grupo', 'estado'], name='deuda_grupo_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.UniqueConstraint(fields=('grupo', 'participante'), name='deuda_unica_por_grupo_participante'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('monto_original__gt', Decimal('0.00'))), name='deuda_monto_original_positivo'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_pendiente__gte', Decimal('0.00'))), name='deuda_saldo_no_negativo'),
        ),
    ]
