# Generated by Django 6.0.5 on 2026-07-26 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_group_fecha_generacion_saldos_closingbalance_debt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityhistory',
            name='tipo_accion',
            field=models.CharField(choices=[('actividad_creada', 'Actividad creada'), ('actividad_actualizada', 'Actividad actualizada'), ('actividad_cerrada_automaticamente', 'Actividad cerrada automáticamente'), ('participante_ingreso', 'Participante agregado'), ('participante_retiro', 'Participante retirado'), ('participante_reingreso', 'Participante reingresado'), ('gasto_creado', 'Gasto creado'), ('gasto_actualizado', 'Gasto actualizado'), ('gasto_eliminado', 'Gasto eliminado'), ('pago_creado', 'Pago creado'), ('responsable_deudas_asignado', 'Responsable de deudas asignado'), ('responsable_deudas_cambiado', 'Responsable de deudas cambiado')], max_length=40),
        ),
        migrations.CreateModel(
            name='DebtReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable_username', models.CharField(max_length=150)),
                ('asignado_por_username', models.CharField(max_length=150)),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_fin', models.DateTimeField(blank=True, editable=False, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsables_deudas_asignados', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_responsable_deudas', to='expenses.group')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_revision_deudas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_asignacion', '-id'],
                'indexes': [models.Index(fields=['grupo', 'vigente'], name='resp_deuda_grupo_vig_idx'), models.Index(fields=['responsable', 'vigente'], name='resp_deuda_user_vig_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('grupo',), name='responsable_deudas_vigente_unico_por_grupo'), models.CheckConstraint(condition=models.Q(models.Q(('fecha_fin__isnull', True), ('vigente', True)), models.Q(('fecha_fin__isnull', False), ('vigente', False)), _connector='OR'), name='responsable_deudas_vigencia_fecha_consistentes')],
            },
        ),
    ]
