# Generated by Django 6.0.5 on 2026-07-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_alter_activityhistory_tipo_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='caso_excepcional_todos_deben',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='group',
            name='fecha_deteccion_todos_deben',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='tipo_accion',
            field=models.CharField(choices=[('actividad_creada', 'Actividad creada'), ('actividad_actualizada', 'Actividad actualizada'), ('actividad_cerrada_automaticamente', 'Actividad cerrada automáticamente'), ('participante_ingreso', 'Participante agregado'), ('participante_retiro', 'Participante retirado'), ('participante_reingreso', 'Participante reingresado'), ('gasto_creado', 'Gasto creado'), ('gasto_actualizado', 'Gasto actualizado'), ('gasto_eliminado', 'Gasto eliminado'), ('pago_creado', 'Pago creado'), ('responsable_deudas_asignado', 'Responsable de deudas asignado'), ('responsable_deudas_cambiado', 'Responsable de deudas cambiado'), ('caso_todos_deben_detectado', 'Caso excepcional: todos deben')], max_length=40),
        ),
    ]
