# Generated by Django 6.0.5 on 2026-07-26 20:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_group_caso_excepcional_todos_deben_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityhistory',
            name='tipo_accion',
            field=models.CharField(choices=[('actividad_creada', 'Actividad creada'), ('actividad_actualizada', 'Actividad actualizada'), ('actividad_cerrada_automaticamente', 'Actividad cerrada automáticamente'), ('participante_ingreso', 'Participante agregado'), ('participante_retiro', 'Participante retirado'), ('participante_reingreso', 'Participante reingresado'), ('gasto_creado', 'Gasto creado'), ('gasto_actualizado', 'Gasto actualizado'), ('gasto_eliminado', 'Gasto eliminado'), ('pago_creado', 'Pago creado'), ('responsable_deudas_asignado', 'Responsable de deudas asignado'), ('responsable_deudas_cambiado', 'Responsable de deudas cambiado'), ('caso_todos_deben_detectado', 'Caso excepcional: todos deben'), ('solicitud_resolucion_creada', 'Solicitud de resolución creada')], max_length=40),
        ),
        migrations.CreateModel(
            name='DebtResolutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nombre', models.CharField(max_length=100)),
                ('solicitante_username', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('evidencia', models.FileField(upload_to=expenses.models.ruta_evidencia_resolucion, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='La evidencia debe estar en formato PDF, JPG, JPEG o PNG.')])),
                ('evidencia_nombre_original', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente_revision', 'Pendiente de revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente_revision', max_length=25)),
                ('decision', models.CharField(blank=True, choices=[('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=15, null=True)),
                ('observacion_revision', models.TextField(blank=True, default='')),
                ('revisado_por_username', models.CharField(blank=True, default='', max_length=150)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_revision', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_resolucion', to='expenses.debt')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_resolucion_deudas', to='expenses.group')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_deuda_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_resolucion_deudas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio', '-id'],
                'indexes': [models.Index(fields=['deuda', 'estado', '-fecha_envio'], name='sol_deuda_estado_fecha_idx'), models.Index(fields=['solicitante', '-fecha_envio'], name='sol_user_fecha_idx'), models.Index(fields=['grupo', 'estado'], name='sol_grupo_estado_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'pendiente_revision')), fields=('deuda',), name='solicitud_pendiente_unica_por_deuda'), models.CheckConstraint(condition=models.Q(models.Q(('decision__isnull', True), ('estado', 'pendiente_revision'), ('fecha_revision__isnull', True), ('revisado_por__isnull', True)), models.Q(('decision', 'aprobada'), ('estado', 'aprobada'), ('fecha_revision__isnull', False), ('revisado_por__isnull', False)), models.Q(('decision', 'rechazada'), ('estado', 'rechazada'), ('fecha_revision__isnull', False), ('revisado_por__isnull', False)), _connector='OR'), name='solicitud_revision_estado_consistente')],
            },
        ),
    ]
