# Generated by Django 6.0.5 on 2026-07-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_alter_activityhistory_tipo_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityhistory',
            name='tipo_accion',
            field=models.CharField(choices=[('actividad_creada', 'Actividad creada'), ('actividad_actualizada', 'Actividad actualizada'), ('actividad_cerrada_automaticamente', 'Actividad cerrada automáticamente'), ('participante_ingreso', 'Participante agregado'), ('participante_retiro', 'Participante retirado'), ('participante_reingreso', 'Participante reingresado'), ('gasto_creado', 'Gasto creado'), ('gasto_actualizado', 'Gasto actualizado'), ('gasto_eliminado', 'Gasto eliminado'), ('pago_creado', 'Pago creado'), ('responsable_deudas_asignado', 'Responsable de deudas asignado'), ('responsable_deudas_cambiado', 'Responsable de deudas cambiado'), ('caso_todos_deben_detectado', 'Caso excepcional: todos deben'), ('solicitud_resolucion_creada', 'Solicitud de resolución creada'), ('solicitud_resolucion_aprobada', 'Solicitud de resolución aprobada'), ('solicitud_resolucion_rechazada', 'Solicitud de resolución rechazada')], max_length=40),
        ),
    ]
