# Generated by Django 6.0.5 on 2026-07-27 14:53

import django.core.validators
import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_alter_activityhistory_tipo_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtresolutionrequest',
            name='evidencia',
            field=models.FileField(blank=True, upload_to=expenses.models.ruta_evidencia_resolucion, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='La evidencia debe estar en formato PDF, JPG, JPEG o PNG.')]),
        ),
        migrations.AlterField(
            model_name='debtresolutionrequest',
            name='evidencia_nombre_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
