from django.urls import path

from .views import (
    AddParticipantView,
    ExpenseCreateView,
    ExpenseDetailView,
    GroupBalanceView,
    GroupDebtView,
    GroupDetailView,
    GroupEconomicSummaryView,
    GroupListCreateView,
    GroupMembershipHistoryView,
    PaymentCreateView,
    RemoveParticipantView,
    UserListView,
    prueba_api,
)


urlpatterns = [
    path(
        "prueba/",
        prueba_api,
        name="prueba_api",
    ),
    path(
        "grupos/",
        GroupListCreateView.as_view(),
        name="listar_crear_grupos",
    ),
    path(
        "grupos/<int:pk>/",
        GroupDetailView.as_view(),
        name="detalle_grupo",
    ),
    path(
        "usuarios/",
        UserListView.as_view(),
        name="listar_usuarios",
    ),
    path(
        "grupos/<int:pk>/participantes/",
        AddParticipantView.as_view(),
        name="agregar_participante",
    ),
    path(
        "grupos/<int:pk>/participantes/<int:usuario_id>/",
        RemoveParticipantView.as_view(),
        name="eliminar_participante",
    ),
    path(
        "grupos/<int:pk>/membresias/",
        GroupMembershipHistoryView.as_view(),
        name="historial_membresias_grupo",
    ),
    path(
        "grupos/<int:pk>/gastos/",
        ExpenseCreateView.as_view(),
        name="registrar_gasto",
    ),
    path(
        "grupos/<int:grupo_id>/gastos/<int:gasto_id>/",
        ExpenseDetailView.as_view(),
        name="detalle_gasto",
    ),
    path(
        "grupos/<int:pk>/resumen-economico/",
        GroupEconomicSummaryView.as_view(),
        name="consultar_resumen_economico_grupo",
    ),
    path(
        "grupos/<int:pk>/balances/",
        GroupBalanceView.as_view(),
        name="consultar_balances_grupo",
    ),
    path(
        "grupos/<int:pk>/deudas/",
        GroupDebtView.as_view(),
        name="consultar_deudas_grupo",
    ),
    path(
        "grupos/<int:pk>/pagos/",
        PaymentCreateView.as_view(),
        name="registrar_pago",
    ),
]