from django.urls import path

from .views import (
    ActivityHistoryListView,
    AddParticipantView,
    ExpenseCreateView,
    ExpenseDetailView,
    GroupBalanceView,
    GroupClosingBalanceView,
    GroupDebtResolutionRequestDecisionView,
    GroupDebtResolutionRequestReviewListView,
    GroupDebtResponsibleView,
    GroupDebtReviewView,
    GroupDebtView,
    GroupDetailView,
    GroupEconomicSummaryView,
    GroupListCreateView,
    GroupMembershipHistoryView,
    GroupOwnDebtView,
    NotificationListView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
    OwnDebtDetailView,
    OwnDebtListView,
    OwnDebtResolutionRequestDetailView,
    OwnDebtResolutionRequestListCreateView,
    ParticipantDebtWarningView,
    PaymentCreateView,
    PaymentDetailView,
    RemoveParticipantView,
    UserListView,
    prueba_api,
)


urlpatterns = [
    path(
        "prueba/",
        prueba_api,
        name="prueba_api",
    ),
    path(
        "grupos/",
        GroupListCreateView.as_view(),
        name="listar_crear_grupos",
    ),
    path(
        "grupos/<int:pk>/",
        GroupDetailView.as_view(),
        name="detalle_grupo",
    ),
    path(
        "usuarios/",
        UserListView.as_view(),
        name="listar_usuarios",
    ),
    path(
        (
            "grupos/<int:pk>/participantes/"
            "<int:usuario_id>/advertencia-deudas/"
        ),
        ParticipantDebtWarningView.as_view(),
        name="consultar_advertencia_deudas_participante",
    ),
    path(
        "grupos/<int:pk>/participantes/",
        AddParticipantView.as_view(),
        name="agregar_participante",
    ),
    path(
        "grupos/<int:pk>/participantes/<int:usuario_id>/",
        RemoveParticipantView.as_view(),
        name="eliminar_participante",
    ),
    path(
        "grupos/<int:pk>/membresias/",
        GroupMembershipHistoryView.as_view(),
        name="historial_membresias_grupo",
    ),
    path(
        "grupos/<int:pk>/historial/",
        ActivityHistoryListView.as_view(),
        name="historial_actividad",
    ),
    path(
        "grupos/<int:pk>/responsable-deudas/",
        GroupDebtResponsibleView.as_view(),
        name="gestionar_responsable_deudas",
    ),
    path(
        (
            "grupos/<int:pk>/solicitudes-deuda/"
        ),
        GroupDebtResolutionRequestReviewListView.as_view(),
        name="listar_solicitudes_deuda_para_revision",
    ),
    path(
        (
            "grupos/<int:pk>/solicitudes-deuda/"
            "<int:solicitud_id>/"
        ),
        GroupDebtResolutionRequestDecisionView.as_view(),
        name="decidir_solicitud_resolucion_deuda",
    ),
    path(
        "grupos/<int:pk>/mi-deuda/",
        GroupOwnDebtView.as_view(),
        name="consultar_deuda_propia",
    ),
    path(
        "grupos/<int:pk>/revision-deudas/",
        GroupDebtReviewView.as_view(),
        name="revisar_deudas_grupo",
    ),
    path(
        "grupos/<int:pk>/gastos/",
        ExpenseCreateView.as_view(),
        name="registrar_gasto",
    ),
    path(
        "grupos/<int:grupo_id>/gastos/<int:gasto_id>/",
        ExpenseDetailView.as_view(),
        name="detalle_gasto",
    ),
    path(
        "grupos/<int:pk>/resumen-economico/",
        GroupEconomicSummaryView.as_view(),
        name="consultar_resumen_economico_grupo",
    ),
    path(
        "grupos/<int:pk>/saldos-cierre/",
        GroupClosingBalanceView.as_view(),
        name="consultar_saldos_cierre_grupo",
    ),
    path(
        "grupos/<int:pk>/balances/",
        GroupBalanceView.as_view(),
        name="consultar_balances_grupo",
    ),
    path(
        "grupos/<int:pk>/deudas/",
        GroupDebtView.as_view(),
        name="consultar_deudas_grupo",
    ),
    path(
        "grupos/<int:pk>/pagos/",
        PaymentCreateView.as_view(),
        name="listar_registrar_pagos",
    ),
    path(
        "grupos/<int:grupo_id>/pagos/<int:pago_id>/",
        PaymentDetailView.as_view(),
        name="detalle_pago",
    ),
    path(
        "mis-deudas/",
        OwnDebtListView.as_view(),
        name="listar_deudas_propias",
    ),
    path(
        "mis-deudas/<int:deuda_id>/",
        OwnDebtDetailView.as_view(),
        name="detalle_deuda_propia",
    ),
    path(
        "mis-deudas/<int:deuda_id>/solicitudes/",
        OwnDebtResolutionRequestListCreateView.as_view(),
        name="listar_crear_solicitudes_deuda_propia",
    ),
    path(
        (
            "mis-deudas/<int:deuda_id>/solicitudes/"
            "<int:solicitud_id>/"
        ),
        OwnDebtResolutionRequestDetailView.as_view(),
        name="detalle_solicitud_deuda_propia",
    ),
    path(
        "notificaciones/",
        NotificationListView.as_view(),
        name="listar_notificaciones",
    ),
    path(
        "notificaciones/marcar-todas-leidas/",
        NotificationMarkAllReadView.as_view(),
        name="marcar_todas_notificaciones_leidas",
    ),
    path(
        "notificaciones/<int:notification_id>/leer/",
        NotificationMarkReadView.as_view(),
        name="marcar_notificacion_leida",
    ),
]